export const metadata = { title: 'Legal, Privacy & Compliance' };

const sections = [
  ['Privacy and personal information', 'We collect only information needed to provide the service, respond to inquiries, manage accounts, administer subscriptions, prevent abuse, and meet legal obligations. We do not store payment card numbers in Pharma Strategies. Payment details should be handled by the authorized payment processor. Access is limited by role, encrypted in transit, and protected with database access rules. Contact us to request access, correction, portability, or deletion where applicable under Canadian privacy law.'],
  ['Canadian privacy notice', 'For Canadian users, our privacy practices are intended to support applicable federal and provincial requirements, including PIPEDA and substantially similar provincial privacy legislation where applicable. We identify purposes, limit collection, retain information only as needed, use reasonable safeguards, and provide a contact route for privacy questions or complaints. Provincial health-information rules may apply to customer workflows; customers remain responsible for configuring lawful notices, consents, retention, and access procedures for their own records.'],
  ['Age and permitted use', 'The service is for businesses and authorized professional users. You must be at least 18 years old and legally able to enter an agreement. Do not use the service for unlawful activity, emergency care, diagnosis, or any purpose that requires a regulated clinical or legal decision without appropriate professional oversight.'],
  ['Terms of service', 'Use of Pharma Strategies is subject to an order or subscription agreement, these terms, and applicable law. Customers are responsible for account security, accurate information, lawful instructions, permissions, retention, and the content they upload. We may suspend access for abuse, security threats, non-payment, or legal requirements. Service descriptions and availability may change.'],
  ['Security and incident response', 'We use access controls, least-privilege database policies, server-side administration checks, encrypted transport, audit records, and private server-side destination redirects. No online service can promise zero risk. If we confirm a breach, we will investigate, contain, preserve evidence, meet applicable notification duties, and communicate with affected customers and regulators as required.'],
  ['Healthcare and regulated records', 'Pharma Strategies is a software platform, not a healthcare provider, pharmacy, legal advisor, or regulator. Customers must determine whether their use involves personal health information, controlled-substance records, or other regulated data and must complete their own compliance assessment before production use.'],
  ['Contact and governing terms', 'Privacy questions, requests, and incident notices should be sent through the contact form. These pages are a general product notice, not legal advice, and should be reviewed by qualified Canadian counsel for your business, province, contracts, retention schedule, and regulated workflows before launch.'],
] as const;

export default function LegalPage() {
  return <main className="mx-auto max-w-4xl px-4 py-20 sm:px-6 lg:px-8"><div className="rounded-3xl border border-navy-100 bg-white p-8 shadow-sm sm:p-12"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-teal-600">Pharma Strategies legal centre</p><h1 className="mt-4 font-heading text-4xl font-bold tracking-tight text-navy-900">Legal, privacy & compliance</h1><p className="mt-5 text-lg leading-relaxed text-navy-600">Clear operating rules for customers, users, and Canadian privacy expectations. Last updated October 6, 2026.</p><div className="mt-12 space-y-10">{sections.map(([title, body]) => <section key={title}><h2 className="font-heading text-xl font-semibold text-navy-900">{title}</h2><p className="mt-3 leading-8 text-navy-700">{body}</p></section>)}</div></div></main>;
}
